In [1]:
f = open("a.txt", 'r')
while True:
    line = f.readline()
    if not line: 
        break
    print(line)

f.close()

2 2

1 2

4 5


In [2]:
import os

os.listdir()
os.getcwd()

'F:\\Github\\Coga_OJT'

In [19]:
import glob

textf = "f:\\Github\\Coga_OJT\\*.txt"
flist = glob.glob(textf)
print(flist)

for i in flist:
    f = open(i, 'r')
    while True:
        print(i)
        line = f.readline()
        print(line)
        if not line:
            break
        
# print()
f.close()

['f:\\Github\\Coga_OJT\\a.txt', 'f:\\Github\\Coga_OJT\\b.txt']
2 2

1 2

4 5

2 2

1 0

0 1



In [27]:
import os
import glob

data_path = 'f:/Github/Coga_OJT'

f_list = glob.glob(data_path + '/*.txt')
for i in f_list:
#     print(i)
    f = open(i, 'r')
    while True:
#         print(i)
        line = f.readline()
        print(line)
        if not line:
            break
    
f.close()

2 2

1 2

4 5

2 2

1 0

0 1



In [6]:
import numpy as np

# 행렬의 크기를 사용자 값을 입력받아서 생성
a_r = int(input("A 행렬의 행 수를 입력하시오."))
a_c = int(input("A 행렬의 열 수를 입력하시오."))

b_r = a_c
b_c = int(input("B 행렬의 열 수를 입력하시오."))
# type(a_r)

# 0으로 이루어진 빈 행렬 생성
a_matrix = np.zeros((a_r, a_c))
# print(a_matrix)

b_matrix = np.zeros((b_r, b_c))
# print(b_matrix)


#반복문을 통해 행렬 안의 값들을 설정

for i in range(a_r):
    for j in range(a_c):
        a_matrix[i][j] = int(input("A행렬의 {0}행 {1}열의 값을 입력하시오.".format(i+1, j+1)))
        
for k in range(b_r):
    for l in range(b_c):
        b_matrix[k][l] = int(input("B행렬의 {0}행 {1}열의 값을 입력하시오.".format(k+1, l+1)))
        
print(a_matrix,'\n', b_matrix)

matmul = []
dot = 0
for x in range(a_r):
    matmul_cal = []
    for y in range(a_c):
        result = 0
        for z in range(b_c):
            
            dot = a_matrix[x][z] * b_matrix[z][y]
            print("a_mat = ", a_matrix[x][z], "b_mat = ", b_matrix[z][y])
            print(dot)
            result += dot
        matmul_cal.append(result)
    matmul.append(matmul_cal) # list를 append 함으로써 2차원 -> numpy사용해서 배열을 만들 필요가 없어진다.
print(matmul)

A 행렬의 행 수를 입력하시오.2
A 행렬의 열 수를 입력하시오.2
B 행렬의 열 수를 입력하시오.2
A행렬의 1행 1열의 값을 입력하시오.1
A행렬의 1행 2열의 값을 입력하시오.2
A행렬의 2행 1열의 값을 입력하시오.4
A행렬의 2행 2열의 값을 입력하시오.5
B행렬의 1행 1열의 값을 입력하시오.1
B행렬의 1행 2열의 값을 입력하시오.0
B행렬의 2행 1열의 값을 입력하시오.0
B행렬의 2행 2열의 값을 입력하시오.1
[[1. 2.]
 [4. 5.]] 
 [[1. 0.]
 [0. 1.]]
a_mat =  1.0 b_mat =  1.0
1.0
a_mat =  2.0 b_mat =  0.0
0.0
a_mat =  1.0 b_mat =  0.0
0.0
a_mat =  2.0 b_mat =  1.0
2.0
a_mat =  4.0 b_mat =  1.0
4.0
a_mat =  5.0 b_mat =  0.0
0.0
a_mat =  4.0 b_mat =  0.0
0.0
a_mat =  5.0 b_mat =  1.0
5.0
[[1.0, 2.0], [4.0, 5.0]]


In [7]:
a = []
a[0][1] = 1
print(a)

IndexError: list index out of range

In [6]:
import numpy as np

a = np.array([[1,2,1],[4,5,2]])
b = np.array([[1, 0], [0,1], [1,0]])
c = np.array([[1, 0, 1, 3], [0, 2, 2, 1]])
d = np.array([[2, 0], [0,2], [3, 1], [4, 1]])
e = np.array([[2, 0], [0, 2]])

ab = np.matmul(a, b)
print(ab)
abc = np.matmul(ab, c)
print(abc)
abcd = np.matmul(abc, d)
print(abcd)
abcde = np.matmul(abcd, e)
print(abcde)

[[2 2]
 [6 5]]
[[ 2  4  6  8]
 [ 6 10 16 23]]
[[ 54  22]
 [152  59]]
[[108  44]
 [304 118]]
